name : SMU BIA
description : SMU Business Intelligence & Analytics
keyword : 
url : smubia.org
email : limkopi@smubia.org
twitter : smubia
github : smubia
author : Gabriel Chuan
year : 2017
markdown : kramdown
exclude :
  - node_modules
