name : SMU BIA
description : SMU Business Intelligence & Analytics
keyword : smu, business intelligence, analytics, data science, co-learning, data projects
url : "localhost:4000"
email : limkopi@smubia.org
twitter : smubia
github : smubia
author : Gabriel Chuan
year : 2017
markdown : kramdown
exclude :
  - node_modules
